### ISSUE TITLE
Bailey's Hour Log

### ISSUE THREAD

**Issue by hetvit27** [hetvit27/issuerepo#2]
Overall Goals:

- [X] Successfully call ChatGPT API from Java file
- [x] Set up secret api key in github repository and connect it to backend code
- [x] Set up Javascript file on frontend to display results
- [x] Add filtering and other specification features 
- [x] Set up pickup line generator

Week of 5-15:

Spent about 3 hours.

- Spent most of the time planning out features with Don
- Started setting up backend:

1. Initialized DatingProfile.java which holds profile/interests for each person
2. Initialized DatingProfileJpaRepository.java and DatingProfileApiController.java

Week of 5-22:

Spent about 7 hours.

- Created ChatGPT.java dedicated to ChatGPT integration with help of Don:

1. Used secret API key from OpenAI stored in Github repo and HttpUrlConnection object to make calls to model
2. Tuned to generate pickup lines based on a given topic

Week of 5-29:

Spent about 10 hours.

- Created pickup line generator relying on ChatGPT API:

1. Utilizes JQuery table that automatically updates in real time as more pickup lines are added
2. Automatically copy pickup lines to clipboard by simply clicking on them
3. Loading image to add more interactability for users

**Comment by horizon-ab** [comment]
Rizz AI W
